<header>
    <div>
        <img>
    </div>
    <nav>
        <ul>
            <li>メニュー１</li>
            <li>メニュー２</li>
            <li>メニュー３</li>
            <li>メニュー４</li>
            <li>メニュー５</li>
        </ul>
    </nav>
</header>